

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graphs
    username: postgres
    password: marcus

  #drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
     ddl-auto: update

schedule:
  lcps:
    url: https://lcps.nu/wp-content/uploads/covid-19-datafeed.csv
    name: "Load LCPS data"
    cron: "0 30 14 * * *"

server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024